using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using System.Reflection;

namespace testcases.CWE129_Improper_Validation_of_Array_Index
{
	class Program {

		static void Main(string[] args) {
			
			if(args.Any()) {
			
				if(args[0].Equals("-h", StringComparison.OrdinalIgnoreCase) || 
                   args[0].Equals("--help", StringComparison.OrdinalIgnoreCase)) {
			
					Console.WriteLine("To use this main, you can either run the program with no " +
					"command line arguments to run all test cases or you can specify one or more classes to test");
					System.Environment.Exit(1);
				}
				
				/* User supplied some class names on the command line, just use those with introspection
				 *
				 * string classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
				 *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
				 * could read class names from command line or use
				 * http://sadun-util.sourceforge.net/api/org/sadun/util/
				 * ClassPackageExplorer.html
				 */

				foreach (string className in args) {

					try {
						
						/* String classNameWithPackage = "testcases." + className; */
						
						/* Console.WriteLine("classNameWithPackage = " + classNameWithPackage); */

						Type myClass = Type.GetType(className);
						object myObject = Activator.CreateInstance(myClass);
						myClass.InvokeMember("runTest", 
							BindingFlags.InvokeMethod | BindingFlags.Instance | BindingFlags.Public, 
							null, 
							myObject, 
							new object[] { className });

					} catch (Exception ex) {

						Console.WriteLine("Could not run test for class " + className);
						Console.WriteLine(ex.StackTrace);

					}
					
					Console.WriteLine(""); /* leave a blank line between classes */

				}

			} else {
			
				/* No command line args were used, we want to run every testcase */
				
				/* needed to separate these calls into other methods because
				   we were running into the size limit Java has for a single method */
				RunTestCWE1();
				RunTestCWE2();
				RunTestCWE3();
				RunTestCWE4();
				RunTestCWE5();
				RunTestCWE6();
				RunTestCWE7();
				RunTestCWE8();
				RunTestCWE9();
			}			
		}

	private static void RunTestCWE1() {
	/* BEGIN-AUTOGENERATED-CSHARP-TESTS-1 */
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_01()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_01");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_02()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_02");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_03()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_03");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_04()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_04");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_05()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_05");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_06()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_06");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_07()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_07");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_08()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_08");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_09()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_09");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_10()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_10");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_11()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_11");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_12()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_12");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_13()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_13");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_14()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_14");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_15()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_15");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_16()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_16");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_17()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_17");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_21()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_21");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_22a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_22a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_31()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_31");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_41()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_41");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_42()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_42");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_45()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_45");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_51a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_51a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_52a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_52a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_53a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_53a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_54a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_54a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_61a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_61a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_66a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_66a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_67a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_67a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_68a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_68a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_71a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_71a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_72a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_72a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_73a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_73a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_74a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_74a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_75a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_75a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_81a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_max_81a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_01()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_01");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_02()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_02");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_03()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_03");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_04()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_04");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_05()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_05");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_06()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_06");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_07()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_07");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_08()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_08");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_09()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_09");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_10()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_10");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_11()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_11");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_12()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_12");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_13()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_13");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_14()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_14");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_15()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_15");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_16()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_16");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_17()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_17");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_21()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_21");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_22a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_22a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_31()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_31");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_41()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_41");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_42()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_42");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_45()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_45");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_51a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_51a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_52a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_52a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_53a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_53a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_54a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_54a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_61a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_61a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_66a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_66a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_67a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_67a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_68a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_68a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_71a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_71a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_72a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_72a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_73a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_73a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_74a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_74a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_75a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_75a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_81a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_check_min_81a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_01()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_01");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_02()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_02");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_03()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_03");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_04()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_04");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_05()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_05");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_06()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_06");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_07()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_07");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_08()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_08");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_09()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_09");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_10()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_10");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_11()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_11");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_12()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_12");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_13()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_13");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_14()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_14");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_15()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_15");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_16()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_16");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_17()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_17");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_21()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_21");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_22a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_22a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_31()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_31");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_41()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_41");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_42()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_42");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_45()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_45");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_51a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_51a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_52a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_52a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_53a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_53a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_54a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_54a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_61a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_61a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_66a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_66a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_67a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_67a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_68a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_68a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_71a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_71a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_72a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_72a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_73a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_73a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_74a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_74a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_75a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_75a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_81a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_read_no_check_81a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_01()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_01");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_02()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_02");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_03()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_03");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_04()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_04");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_05()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_05");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_06()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_06");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_07()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_07");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_08()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_08");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_09()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_09");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_10()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_10");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_11()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_11");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_12()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_12");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_13()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_13");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_14()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_14");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_15()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_15");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_16()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_16");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_17()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_17");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_21()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_21");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_22a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_22a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_31()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_31");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_41()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_41");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_42()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_42");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_45()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_45");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_51a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_51a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_52a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_52a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_53a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_53a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_54a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_54a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_61a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_61a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_66a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_66a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_67a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_67a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_68a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_68a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_71a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_71a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_72a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_72a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_73a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_73a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_74a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_74a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_75a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_75a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_size_81a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_size_81a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_01()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_01");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_02()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_02");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_03()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_03");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_04()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_04");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_05()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_05");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_06()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_06");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_07()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_07");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_08()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_08");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_09()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_09");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_10()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_10");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_11()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_11");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_12()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_12");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_13()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_13");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_14()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_14");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_15()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_15");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_16()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_16");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_17()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_17");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_21()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_21");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_22a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_22a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_31()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_31");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_41()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_41");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_42()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_42");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_45()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_45");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_51a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_51a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_52a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_52a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_53a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_53a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_54a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_54a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_61a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_61a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_66a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_66a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_67a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_67a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_68a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_68a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_71a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_71a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_72a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_72a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_73a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_73a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_74a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_74a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_75a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_75a");
			(new CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_81a()).RunTest("CWE129_Improper_Validation_of_Array_Index__Random_array_write_no_check_81a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_01()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_01");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_02()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_02");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_03()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_03");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_04()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_04");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_05()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_05");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_06()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_06");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_07()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_07");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_08()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_08");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_09()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_09");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_10()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_10");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_11()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_11");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_12()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_12");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_13()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_13");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_14()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_14");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_15()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_15");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_16()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_16");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_17()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_17");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_21()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_21");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_22a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_22a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_31()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_31");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_41()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_41");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_42()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_42");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_45()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_45");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_51a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_51a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_52a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_52a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_53a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_53a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_54a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_54a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_61a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_61a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_66a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_66a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_67a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_67a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_68a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_68a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_71a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_71a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_72a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_72a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_73a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_73a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_74a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_74a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_75a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_75a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_81a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_max_81a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_01()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_01");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_02()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_02");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_03()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_03");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_04()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_04");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_05()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_05");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_06()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_06");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_07()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_07");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_08()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_08");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_09()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_09");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_10()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_10");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_11()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_11");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_12()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_12");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_13()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_13");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_14()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_14");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_15()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_15");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_16()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_16");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_17()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_17");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_21()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_21");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_22a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_22a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_31()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_31");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_41()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_41");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_42()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_42");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_45()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_45");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_51a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_51a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_52a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_52a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_53a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_53a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_54a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_54a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_61a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_61a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_66a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_66a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_67a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_67a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_68a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_68a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_71a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_71a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_72a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_72a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_73a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_73a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_74a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_74a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_75a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_75a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_81a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_check_min_81a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_01()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_01");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_02()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_02");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_03()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_03");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_04()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_04");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_05()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_05");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_06()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_06");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_07()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_07");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_08()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_08");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_09()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_09");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_10()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_10");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_11()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_11");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_12()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_12");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_13()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_13");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_14()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_14");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_15()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_15");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_16()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_16");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_17()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_17");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_21()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_21");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_22a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_22a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_31()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_31");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_41()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_41");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_42()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_42");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_45()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_45");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_51a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_51a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_52a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_52a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_53a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_53a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_54a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_54a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_61a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_61a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_66a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_66a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_67a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_67a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_68a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_68a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_71a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_71a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_72a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_72a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_73a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_73a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_74a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_74a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_75a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_75a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_81a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_read_no_check_81a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_01()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_01");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_02()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_02");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_03()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_03");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_04()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_04");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_05()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_05");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_06()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_06");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_07()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_07");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_08()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_08");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_09()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_09");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_10()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_10");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_11()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_11");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_12()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_12");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_13()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_13");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_14()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_14");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_15()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_15");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_16()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_16");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_17()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_17");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_21()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_21");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_22a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_22a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_31()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_31");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_41()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_41");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_42()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_42");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_45()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_45");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_51a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_51a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_52a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_52a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_53a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_53a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_54a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_54a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_61a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_61a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_66a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_66a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_67a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_67a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_68a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_68a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_71a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_71a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_72a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_72a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_73a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_73a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_74a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_74a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_75a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_75a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_81a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_size_81a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_01()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_01");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_02()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_02");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_03()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_03");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_04()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_04");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_05()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_05");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_06()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_06");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_07()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_07");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_08()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_08");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_09()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_09");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_10()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_10");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_11()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_11");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_12()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_12");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_13()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_13");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_14()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_14");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_15()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_15");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_16()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_16");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_17()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_17");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_21()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_21");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_22a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_22a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_31()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_31");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_41()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_41");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_42()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_42");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_45()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_45");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_51a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_51a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_52a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_52a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_53a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_53a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_54a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_54a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_61a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_61a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_66a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_66a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_67a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_67a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_68a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_68a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_71a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_71a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_72a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_72a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_73a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_73a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_74a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_74a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_75a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_75a");
			(new CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_81a()).RunTest("CWE129_Improper_Validation_of_Array_Index__ReadLine_array_write_no_check_81a");
			/* END-AUTOGENERATED-CSHARP-TESTS-1 */
	}

	private static void RunTestCWE2() {
	/* BEGIN-AUTOGENERATED-CSHARP-TESTS-2 */

			/* END-AUTOGENERATED-CSHARP-TESTS-2 */
	}

	private static void RunTestCWE3() {
	/* BEGIN-AUTOGENERATED-CSHARP-TESTS-3 */

			/* END-AUTOGENERATED-CSHARP-TESTS-3 */
	}

	private static void RunTestCWE4() {
	/* BEGIN-AUTOGENERATED-CSHARP-TESTS-4 */

			/* END-AUTOGENERATED-CSHARP-TESTS-4 */
	}

	private static void RunTestCWE5() {
	/* BEGIN-AUTOGENERATED-CSHARP-TESTS-5 */

			/* END-AUTOGENERATED-CSHARP-TESTS-5 */
	}

	private static void RunTestCWE6() {
	/* BEGIN-AUTOGENERATED-CSHARP-TESTS-6 */

			/* END-AUTOGENERATED-CSHARP-TESTS-6 */
	}

	private static void RunTestCWE7() {
	/* BEGIN-AUTOGENERATED-CSHARP-TESTS-7 */

			/* END-AUTOGENERATED-CSHARP-TESTS-7 */
	}

	private static void RunTestCWE8() {
	/* BEGIN-AUTOGENERATED-CSHARP-TESTS-8 */

			/* END-AUTOGENERATED-CSHARP-TESTS-8 */
	}

	private static void RunTestCWE9() {
	/* BEGIN-AUTOGENERATED-CSHARP-TESTS-9 */

			/* END-AUTOGENERATED-CSHARP-TESTS-9 */
	}
}
}